// ADVISOR_36EA.c
// Generated by decompiling ADVISOR.EXE
// using Reko decompiler version 0.11.3.0.

#include "ADVISOR.h"

// 36EA:00C3: Register word16 fn36EA_00C3(Register (ptr16 Eq_36) ds)
// Called from:
//      fn3704_00C8
word16 fn36EA_00C3(struct seg3ADE_t * ds)
{
	Eq_62 wLoc04;
	word16 wLoc02;
	fn2FCE_3BF3(&seg3ADE_t::ptrFFFFA71E, ds);
	fn2FCE_3BF3(&seg3ADE_t::ptrFFFFA736, ds);
	word16 seg3ADE_t::* si_24;
	word16 bp_19 = fn2FCE_3A5D((ds->*ds->ptrB022).ptr0002, ds, wLoc04, wLoc02, out si_24);
	ds->wB03C = 0x00;
	ds->wB038 = bp_19;
	return ds->*si_24 + 0x30;
}

