// ADVISOR_2FCE.c
// Generated by decompiling ADVISOR.EXE
// using Reko decompiler version 0.11.3.0.

#include "ADVISOR.h"

struct seg2FCE_t * g_ptr2FCE0 = null; // 0002FCE0
// 2FCE:3A40: Register word16 fn2FCE_3A40(Register byte al, Register (memptr (ptr16 Eq_36) Eq_39) bp, Register (ptr16 Eq_36) ds, Register out (ptr16 Eq_41) bxOut)
// Called from:
//      fn2FCE_3AAC
//      fn2FCE_3B1D
word16 fn2FCE_3A40(byte al, struct Eq_39 seg3ADE_t::* bp, struct seg3ADE_t * ds, struct Eq_41 & bxOut)
{
	struct Eq_39 seg3ADE_t::* bx_10 = bp;
	do
	{
		bx_10 = (ds->*bx_47).ptr0000;
		bx_47 = bx_10;
	} while (bx_10 != ds->ptrB03A);
	struct Eq_41 * bx_21 = (ds->*bx_47).ptr0004;
	word16 ax_33 = bx_21->a0000[(int16) al];
	bxOut = bx_21;
	return ax_33;
}

// 2FCE:3A5D: Register mp16 fn2FCE_3A5D(Register (ptr16 Eq_60) dx, Register (ptr16 Eq_36) ds, Stack Eq_62 wArg00, Stack word16 wArg02, Register out ptr16 siOut)
// Called from:
//      fn36EA_00C3
mp16 fn2FCE_3A5D(struct Eq_60 * dx, struct seg3ADE_t * ds, Eq_62 wArg00, word16 wArg02, ptr16 & siOut)
{
	mp16 fp;
	struct Eq_66 * ss;
	ptr16 si;
	Eq_68 ax_14 = fp - dx->w0022;
	if (ax_14 < 0x00 || (ax_14 < 0x0A || ax_14 - 0x0A < ds->tB020))
	{
		mp16 sp_24 = fp - 2;
		cu16 bx_34 = 0x00;
		if (true)
			bx_34 = 0x9007;
		Eq_103 cx_44 = ds->tACB0;
		if (cx_44 == 0x00)
		{
			struct Eq_39 seg3ADE_t::* bx_52;
			struct Eq_39 seg3ADE_t::* cx_48 = fp - 2;
			if (fp - 2 == ds->ptrB03A)
			{
l2FCE_3DDA:
				sp_24 = fp - 4;
				bx_52 = fp - 4;
			}
			else
			{
				do
				{
					bx_52 = cx_48;
					if (cx_48 == &seg3ADE_t::t0000)
						goto l2FCE_3DDA;
					cx_48 = (ds->*cx_48).ptr0000;
				} while (cx_48 != ds->ptrB03A);
			}
			struct Eq_121 Eq_66::* sp_71 = sp_24 - 2;
			(ss->*sp_71).ptr0000 = bx_52;
			ds->wB056 = bx_34;
			(ss->*sp_71).ptrFFFFFFFE = bx_52;
			fn2FCE_3BF3(&seg3ADE_t::ptrFFFFA776, ds);
			ds->bA7A0 = 0x00;
			word16 ax_109 = fn3704_038E(ds);
			struct Eq_121 Eq_66::* sp_106 = sp_71;
			if (ds->bB057 != 0x98)
				(seg2FCE->*ds->ptrACA8)();
			ds->bB05A = 0x00;
			ptr16 si_123;
			mp16 bp_119 = fn2FCE_52F8(ax_109, ds, (ss->*sp_106).ptr0000, out si_123);
			siOut = si_123;
			return bp_119;
		}
		else
		{
			cx_44();
			siOut = si;
			return fp - 2;
		}
	}
	else
	{
		ds->tABC2 = wArg00;
		ds->wABC4 = wArg02;
		ds->ptrB03A = fp + 2;
		++ds->wB03C;
		ds->tABC2();
		siOut = si;
		return fp + 2;
	}
}

// 2FCE:3AAC: Register word16 fn2FCE_3AAC(Sequence (ptr32 Eq_177) ss_bp, Register (ptr16 Eq_36) ds)
// Called from:
//      fn2FCE_52F8
word16 fn2FCE_3AAC(struct Eq_177 * ss_bp, struct seg3ADE_t * ds)
{
	struct Eq_39 seg3ADE_t::* bp = (word16) ss_bp;
	if (ds->wB056 < 0x9400)
	{
		fn2FCE_3E33(0x8008);
		word16 bx_144;
		if (fn2FCE_3A40(0x0A, bp, ds, out bx_144) != &Eq_282::w0000)
		{
			fn2FCE_3E33(0x800A);
			uint16 ax_36;
			if (!fn2FCE_3B1D(ss_bp->w0002, bp, ds, out ax_36))
				fn2FCE_3E33(0x9400);
			else
			{
				fn2FCE_3E91(ax_36, &seg2FCE_t::t3E88);
				fn2FCE_3E33(0x8009);
			}
		}
	}
	fn2FCE_3E33(0x800B);
	struct Eq_190 * bx_81;
	fn2FCE_3A40(0x00, bp, ds, out bx_81);
	byte Eq_190::* si_87 = Eq_190::a0002;
	word16 cx_104;
	for (cx_104 = 0x08; cx_104 != 0x00; --cx_104)
	{
		++si_87;
		fn2FCE_3E88(bx_81->*si_87);
	}
	fn2FCE_3E33(0x800C);
	byte ah_127 = fn2FCE_3E88(0x3A);
	cup16 dx_128 = ss_bp->w0002;
	byte dh_129 = SLICE(dx_128, byte, 8);
	byte dl_131 = (byte) dx_128;
	return fn2FCE_3B13(SEQ(ah_127, dh_129), dl_131);
}

// 2FCE:3B13: Register word16 fn2FCE_3B13(Sequence word16 ah_dh, Register byte dl)
// Called from:
//      fn2FCE_3AAC
word16 fn2FCE_3B13(word16 ah_dh, byte dl)
{
	word16 ax_16 = SEQ(SLICE(fn2FCE_3E73(ah_dh), byte, 8), dl);
	return fn2FCE_3E73(ax_16);
}

// 2FCE:3B1D: FlagGroup bool fn2FCE_3B1D(Register cup16 ax, Register (memptr (ptr16 Eq_36) Eq_39) bp, Register (ptr16 Eq_36) ds, Register out ptr16 axOut)
// Called from:
//      fn2FCE_3AAC
bool fn2FCE_3B1D(cup16 ax, struct Eq_39 seg3ADE_t::* bp, struct seg3ADE_t * ds, ptr16 & axOut)
{
	struct Eq_282 * bx_17;
	word16 Eq_282::* si_25 = fn2FCE_3A40(0x0A, bp, ds, out bx_17);
	cup16 bx_27 = 0x00;
	ptr16 dx_30 = 0x00;
	while (true)
	{
		cup16 ax_36 = bx_17->*si_25;
		word16 Eq_282::* si_37 = si_25 + 1;
		if (ax_36 == 0x00)
			break;
		if (ax_36 < ax && ax_36 >= bx_27)
		{
			bx_27 = ax_36;
			ptr16 ax_68 = bx_17->*si_37;
			si_25 = si_37 + 1;
			if (ax_36 != bx_27 || ax_68 > dx_30)
				dx_30 = ax_68;
		}
		else
			si_25 = si_37 + 1;
	}
	axOut = dx_30;
	return SLICE(cond(bx_27), bool, 2);
}

// 2FCE:3B84: void fn2FCE_3B84(Register (ptr16 Eq_36) ds)
// Called from:
//      fn3704_00C8
void fn2FCE_3B84(struct seg3ADE_t * ds)
{
	Eq_316 es_si_13 = (ds->*ds->ptrB022).t0000;
	ds->tABCA = (word16) es_si_13;
	ds->ptrABCC = SLICE(es_si_13, selector, 16);
	fn2FCE_3BFF(ds);
	ds->bB035 |= 0x10;
}

// 2FCE:3BF3: Register (memptr (ptr16 Eq_36) (memptr (ptr16 Eq_29) code)) fn2FCE_3BF3(Register (memptr (ptr16 Eq_36) (memptr (ptr16 Eq_29) code)) si, Register (ptr16 Eq_36) ds)
// Called from:
//      fn2FCE_3A5D
//      fn2FCE_4989
//      fn36EA_00C3
<anonymous> seg2FCE_t::* seg3ADE_t::* fn2FCE_3BF3(<anonymous> seg2FCE_t::* seg3ADE_t::* si, struct seg3ADE_t * ds)
{
	word16 cx_15 = ds->*si;
	if (cx_15 != 0x00)
	{
		do
		{
			si = si;
			(seg2FCE->*(ds->*si))();
			cx_15 = cx_36 - 0x01;
			cx_36 = cx_15;
		} while (cx_36 != 0x01);
	}
	return si;
}

// 2FCE:3BFF: void fn2FCE_3BFF(Register (ptr16 Eq_36) ds)
// Called from:
//      fn2FCE_3B84
void fn2FCE_3BFF(struct seg3ADE_t * ds)
{
	fn2FCE_3C0D(ds);
	ds->bB035 &= ~0x14;
	fn3704_038E(ds);
}

// 2FCE:3C0D: void fn2FCE_3C0D(Register (ptr16 Eq_36) ds)
// Called from:
//      fn2FCE_3BFF
void fn2FCE_3C0D(struct seg3ADE_t * ds)
{
	Eq_322 es_bx_12 = ds->tABCA;
	word16 seg3ADE_t::* di_15 = *((word32) es_bx_12 + 24);
	cu16 cx_17 = *((word32) es_bx_12 + 0x0E) - di_15;
	ds->wA77E = 0x00;
	uint16 cx_23;
	for (cx_23 = cx_17 >> 0x01; cx_23 != 0x00; --cx_23)
	{
		ds->*di_15 = 0x00;
		++di_15;
	}
	ds->ptrA780 = di_15;
	ds->ptrB02B = ds;
	fn2FCE_3C68(ds);
}

// 2FCE:3C68: void fn2FCE_3C68(Register (ptr16 Eq_36) ds)
// Called from:
//      fn2FCE_3C0D
void fn2FCE_3C68(struct seg3ADE_t * ds)
{
	mp16 fp;
	if ((ds->bB035 & 0x10) == 0x00)
	{
		Eq_322 es_bx_25 = ds->tABCA;
		Eq_375 di_28 = *((word32) es_bx_25 + 0x0E);
		uint16 cx_33;
		for (cx_33 = *((word32) es_bx_25 + 16) - di_28 >> 0x01; cx_33 != 0x00; --cx_33)
		{
			ds->*di_28 = 0x00;
			di_28 = (word16) di_28 + 2;
		}
	}
	byte seg3ADE_t::* di_36 = seg3ADE_t::aFFFFB04A;
	word16 cx_37;
	for (cx_37 = 0x17; cx_37 != 0x00; --cx_37)
	{
		ds->*di_36 = 0x00;
		++di_36;
	}
	fn2FCE_3C9D(fp - 6, ds, ds);
}

// 2FCE:3C9D: void fn2FCE_3C9D(Register Eq_438 bx, Register (ptr16 Eq_36) es, Register (ptr16 Eq_36) ds)
// Called from:
//      fn2FCE_3C68
void fn2FCE_3C9D(Eq_438 bx, struct seg3ADE_t * es, struct seg3ADE_t * ds)
{
	Eq_454 di_13 = ds->tB01E;
	word16 ax_10 = 0xFE80;
	do
	{
		es->*di_13 = ax_10;
		di_13 = (word16) di_13 + 2;
		ax_10 += 0x02;
	} while (di_13 < bx - 0x04);
}

// 2FCE:3E33: Register cu16 fn2FCE_3E33(Register cu16 ax)
// Called from:
//      fn2FCE_3AAC
//      fn2FCE_52F8
//      fn3704_0310
cu16 fn2FCE_3E33(cu16 ax)
{
	byte ah = SLICE(ax, byte, 8);
	byte al = (byte) ax;
	cu16 ax_14 = ax;
	if (ah == 0x00)
		ax_14 = SEQ(0x10, al);
	struct Eq_476 * dx_19;
	byte Eq_476::* ax_18 = fn2FCE_52F0(ax_14, out dx_19);
	byte Eq_476::* ax_24 = ax_18;
	if (ax_18 == &Eq_476::b0000)
		ax_24 = fn2FCE_52F0(0x10FF, out dx_19);
	byte ah_55 = SLICE(ax_24, byte, 8);
	byte Eq_476::* si_36 = ax_24;
	while (true)
	{
		byte al_45 = dx_19->*si_36;
		++si_36;
		cu16 ax_56 = SEQ(ah_55, al_45);
		if (al_45 == 0x00)
			break;
		ah_55 = fn2FCE_3E88(al_45);
	}
	return ax_56;
}

// 2FCE:3E59: void fn2FCE_3E59(Register byte ah, Register (ptr16 Eq_36) ds)
// Called from:
//      fn2FCE_52F8
void fn2FCE_3E59(byte ah, struct seg3ADE_t * ds)
{
	fn2FCE_3E88(0x0A);
	ds->tA782 = fn2FCE_4F11(ds->tA782, ds);
}

// 2FCE:3E73: Register word16 fn2FCE_3E73(Register word16 ax)
// Called from:
//      fn2FCE_3B13
word16 fn2FCE_3E73(word16 ax)
{
	bcu8 al_8 = (byte) ax;
	byte ah_14 = SLICE(ax, byte, 8);
	fn2FCE_3E80(al_8 >> 0x04, ah_14);
	uint8 al_22 = (byte) ax;
	byte ah_23 = SLICE(ax, byte, 8);
	return fn2FCE_3E80(al_22, ah_23);
}

// 2FCE:3E80: Register word16 fn2FCE_3E80(Register uint8 al, Register byte ah)
// Called from:
//      fn2FCE_3E73
word16 fn2FCE_3E80(uint8 al, byte ah)
{
	byte al_6 = (al & 0x0F) + 0x90;
	byte al_8 = al_6 + 0x40 + (byte) __daa(al_6, &al_6);
	return SEQ(fn2FCE_3E88(al_8), al_8);
}

// 2FCE:3E88: Register byte fn2FCE_3E88(Register byte al)
// Called from:
//      fn2FCE_3AAC
//      fn2FCE_3E33
//      fn2FCE_3E59
//      fn2FCE_3E80
byte fn2FCE_3E88(byte al)
{
	word16 ax;
	msdos_direct_console_output((byte) ax);
	return 0x06;
}

// 2FCE:3E91: void fn2FCE_3E91(Register uint16 ax, Register (memptr (ptr16 Eq_29) code) cx)
// Called from:
//      fn2FCE_3AAC
void fn2FCE_3E91(uint16 ax, <anonymous> seg2FCE_t::* cx)
{
	word16 Eq_568::* fp;
	struct Eq_568 * ss;
	word16 wLoc02;
	word16 Eq_568::* sp_2 = fp;
	word16 dx_10 = 0x00;
	do
	{
		sp_2 -= 2;
		ss->*sp_2 = dx_10;
		uint32 dx_ax_15 = (uint32) ax;
		uint16 ax_19 = (uint16) (dx_ax_15 /u 0x0A);
		uint16 dx_18 = (uint16) (dx_ax_15 % 0x0A);
		ax = ax_19;
		dx_10 = SEQ(SLICE(dx_18, byte, 8), (byte) dx_18 + 0x30);
	} while (ax_19 != 0x00);
	do
		(seg2FCE->*cx)();
	while (wLoc02 != 0x00);
}

// 2FCE:4989: Register word16 fn2FCE_4989(Register (ptr16 Eq_36) ds)
// Called from:
//      fn2FCE_52F8
word16 fn2FCE_4989(struct seg3ADE_t * ds)
{
	ds->bB05A = ~0x00;
	return fn2FCE_3BF3(&seg3ADE_t::ptrFFFFA74C, ds);
}

// 2FCE:4F11: Register word16 fn2FCE_4F11(Register Eq_515 dl, Register (ptr16 Eq_36) ds)
// Called from:
//      fn2FCE_3E59
word16 fn2FCE_4F11(Eq_515 dl, struct seg3ADE_t * ds)
{
	if (dl == ds->tA784)
		dl = ds->tA787;
	word16 dx_17 = SEQ(0x01, dl);
	if (ds->tA787 != dl)
		++dx_17;
	return dx_17;
}

// 2FCE:52F0: Register cu16 fn2FCE_52F0(Register cu16 ax, Register out ptr16 dxOut)
// Called from:
//      fn2FCE_3E33
cu16 fn2FCE_52F0(cu16 ax, ptr16 & dxOut)
{
	ptr16 dx_9;
	cu16 ax_8 = fn3704_0352(ax, out dx_9);
	dxOut = dx_9;
	return ax_8;
}

// 2FCE:52F8: Register word16 fn2FCE_52F8(Register word16 ax, Register (ptr16 Eq_36) ds, Stack (memptr (ptr16 Eq_36) Eq_39) wArg02, Register out ptr16 siOut)
// Called from:
//      fn2FCE_3A5D
word16 fn2FCE_52F8(word16 ax, struct seg3ADE_t * ds, struct Eq_39 seg3ADE_t::* wArg02, ptr16 & siOut)
{
	struct Eq_629 * ss;
	fn2FCE_3E59((byte) ax, ds);
	word16 ax_16 = fn2FCE_3E33(ds->wB056);
	if (ds->wB056 < 0x9800)
		ax_16 = fn2FCE_3AAC(&(ss->*wArg02).ptr0000, ds);
	fn2FCE_3E59((byte) ax_16, ds);
	fn2FCE_4989(ds);
	word16 bp_52 = fn3704_025E(ds, 0x00);
	siOut = fn2FCE_4989(ds);
	return bp_52;
}

<anonymous> seg2FCE_t::* g_ptrFFFFA71E = ;
<anonymous> seg2FCE_t::* g_ptrFFFFA736 = ;
<anonymous> seg2FCE_t::* g_ptrFFFFA74C = ;
<anonymous> seg2FCE_t::* g_ptrFFFFA776 = ;
ui16 g_wFFFFAF70 = 0x6017; // 2ADE:AF70
Eq_730 g_tFFFFAF72 = // 2ADE:AF72
	{
		12238
	};
word16 g_wFFFFAF74 = 22352; // 2ADE:AF74
word16 g_wFFFFAF76 = 62106; // 2ADE:AF76
byte g_bFFFFAFC8 = ~0x08; // 2ADE:AFC8
struct Eq_694 * g_ptrFFFFAFE7 = &g_t0653; // 2ADE:AFE7
byte g_aFFFFAFF0[] = // 2ADE:AFF0
	{
	};
word16 g_wFFFFB012 = ~0x1117; // 2ADE:B012
struct Eq_694 * g_ptrFFFFB014 = &g_tFFFF93CD; // 2ADE:B014
word16 g_wFFFFB016 = 51805; // 2ADE:B016
word16 g_wFFFFB024 = 51035; // 2ADE:B024
byte g_aFFFFB04A[] = // 2ADE:B04A
	{
	};
byte g_aFFFFB082[] = // 2ADE:B082
	{
	};
