// ADVISOR_3ADE.c
// Generated by decompiling ADVISOR.EXE
// using Reko decompiler version 0.11.3.0.

#include "ADVISOR.h"

struct seg3ADE_t * g_ptr3ADE0 = null; // 0003ADE0
byte g_bA71C = 0x00; // 3ADE:A71C
<anonymous> seg2FCE_t::* g_ptrA71E = ;
<anonymous> seg2FCE_t::* g_ptrA736 = ;
<anonymous> seg2FCE_t::* g_ptrA74C = ;
<anonymous> seg2FCE_t::* g_ptrA776 = ;
word16 g_wA77E = 0x00; // 3ADE:A77E
word16 seg3ADE_t::* g_ptrA780 = ;
Eq_515 g_tA782 = // 3ADE:A782
	{
		0x01
	};
Eq_515 g_tA784 = // 3ADE:A784
	{
		0x18
	};
Eq_515 g_tA787 = // 3ADE:A787
	{
		0x18
	};
byte g_bA7A0 = 0x00; // 3ADE:A7A0
Eq_62 g_tABC2 = // 3ADE:ABC2
	{
		0x00
	};
word16 g_wABC4 = 0x00; // 3ADE:ABC4
Eq_322 g_tABCA = // 3ADE:ABCA
	{
		0x00
	};
struct Eq_325 * g_ptrABCC = null; // 3ADE:ABCC
<anonymous> seg2FCE_t::* g_ptrACA8 = ;
Eq_103 g_tACB0 = // 3ADE:ACB0
	{
		0x00
	};
byte g_bAFC8 = 0x3B; // 3ADE:AFC8
Eq_833 g_tAFD5 = // 3ADE:AFD5
	{
		0x00
	};
struct Eq_836 * g_ptrAFD7 = null; // 3ADE:AFD7
struct Eq_877 * g_ptrAFE7 = null; // 3ADE:AFE7
word16 g_wAFE9 = 0x00; // 3ADE:AFE9
byte g_aAFF0[5] = // 3ADE:AFF0
	{
		0x81,
		0x81,
		0x81,
		0x01,
		0x01,
	};
byte g_bB018 = 0x00; // 3ADE:B018
byte g_bB019 = 0x00; // 3ADE:B019
<anonymous> * g_ptrB01A = null; // 3ADE:B01A
Eq_454 g_tB01E = // 3ADE:B01E
	{
		0xB090
	};
Eq_79 g_tB020 = // 3ADE:B020
	{
		0xB111
	};
struct Eq_318 seg3ADE_t::* g_ptrB022 = ;
struct seg3ADE_t * g_ptrB02B = null; // 3ADE:B02B
byte g_bB035 = 0x00; // 3ADE:B035
word16 g_wB038 = 0x00; // 3ADE:B038
struct Eq_39 seg3ADE_t::* g_ptrB03A = ;
word16 g_wB03C = 0x00; // 3ADE:B03C
byte g_bB04A = 0x00; // 3ADE:B04A
cu16 g_wB056 = 0x00; // 3ADE:B056
byte g_bB057 = 0x00; // 3ADE:B057
byte g_bB05A = 0x00; // 3ADE:B05A
word16 g_wB064 = 0x00; // 3ADE:B064
<anonymous> seg3704_t::* g_ptrB06A = ;
<anonymous> * g_ptrB072 = &g_t380E0024; // 3ADE:B072
word16 g_wB074 = 0x380E; // 3ADE:B074
byte g_bB082 = 0x00; // 3ADE:B082
