// ADVISOR_3A61.c
// Generated by decompiling ADVISOR.EXE
// using Reko decompiler version 0.11.3.0.

#include "ADVISOR.h"

struct seg3A61_t * g_ptr3A610 = &g_tFFFF8BFC; // 0003A610
Eq_1134 g_t0010 = // 3A61:0010
	{
		
		{
			0x02
		},
	};
